### ISSUE TITLE
Catchable fatal error: Argument 4

### ISSUE THREAD

**Issue by juppy81** [facebook/php-graph-sdk#958] opened 2018-03-17 12:58 UTC
Salve, da ieri riscontro questo errore nel mio sito che mi impedisce di effettuare il login tramite facebook:

Catchable fatal error: Argument 4 passed to Facebook\FacebookResponse::__construct() must be of the type array, null given, called in /home/mhd-01/www.chetorneo.com/htdocs/php-graph-sdk-5.0.0/src/Facebook/FacebookClient.php on line 225 and defined in /home/mhd-01/www.chetorneo.com/htdocs/php-graph-sdk-5.0.0/src/Facebook/FacebookResponse.php on line 75

Questo problema è sorto senza che io abbia effettuato modifiche, quale può essere il problema?

Per favore vi chiedo aiuto, grazie a tutti.

**Comment by mik1khan** [comment] 2018-03-20 17:45
hello,
    I am having same issue since 17 march. the facebook login was working fine previously but from 17 march it is showing the same error:

Catchable fatal error: Argument 4 passed to Facebook\FacebookResponse::__construct() must be of the type array, null given, called in /home/digmonsters/public_html/facebook-php-sdk/FacebookClient.php on line 225 and defined in /home/digmonsters/public_html/facebook-php-sdk/FacebookResponse.php on line 75

Please let us know what is the issue.

Thanks

**Comment by apascal67** [comment] 2018-03-20 18:01
greetings,
I had the same issue and apparently fixed it by changing the path on the "require_once" php statement on my fb-callback.php file 
from:
require_once __DIR__ . '/facebook-sdk-v5/src/Facebook/autoload.php';
to:
require_once __DIR__ . '/vendor/autoload.php';

this ALL I did and it seems to work just fine again. I hope it works for you.

**Comment by apascal67** [comment] 2018-03-20 18:02
hi,
I posted my answer directly at github. I hope it works for you as well.
have a great week.
thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by petertoth0507** [comment] 2018-05-07 23:46
I have a same problem at https://www.classfund.hu/index.php?r=site/login

I didn't change my code and it was working before a month ago...
Maybe it is a facebook side issue.

message: Argument 4 passed to Facebook\FacebookResponse::__construct() must be of the type array, null given, called in /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/FacebookClient.php on line 225 and defined
file: /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/FacebookResponse.php
line: 75
trace: #0 /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/FacebookClient.php(225): Facebook\FacebookResponse->__construct() #1 /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/Authentication/OAuth2Client.php(277): Facebook\FacebookClient->sendRequest() #2 /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/Authentication/OAuth2Client.php(226): Facebook\Authentication\OAuth2Client->sendRequestWithClientParams() #3 /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/Authentication/OAuth2Client.php(166): Facebook\Authentication\OAuth2Client->requestAnAccessToken() #4 /home/classfun/public_html/chef/protected/vendors/facebook-sdk-v5/Helpers/FacebookRedirectLoginHelper.php(255): Facebook\Authentication\OAuth2Client->getAccessTokenFromCode() #5 /home/classfun/public_html/chef/protected/controllers/SiteController.php(141): Facebook\Helpers\FacebookRedirectLoginHelper->getAccessToken() #6 /home/classfun/public_html/framework/web/actions/CInlineAction.php(49): SiteController->actionFBlogincallback() #7 /home/classfun/public_html/framework/web/CController.php(308): CInlineAction->runWithParams() #8 /home/classfun/public_html/framework/web/CController.php(286): SiteController->runAction() #9 /home/classfun/public_html/framework/web/CController.php(265): SiteController->runActionWithFilters() #10 /home/classfun/public_html/framework/web/CWebApplication.php(282): SiteController->run() #11 /home/classfun/public_html/framework/web/CWebApplication.php(141): CWebApplication->runController() #12 /home/classfun/public_html/framework/base/CApplication.php(184): CWebApplication->processRequest() #13 /home/classfun/public_html/index.php(16): CWebApplication->run()

**Comment by yguedidi** [comment] 2018-06-17 09:30
Closing as it's looks like a solution is found and the issue is not related to the SDK itself.

**Closed by yguedidi** 2018-06-17 09:30 UTC
