### ISSUE TITLE
auto post problem

### ISSUE THREAD

**Issue by Mokhir1212** [facebook/php-graph-sdk#737] opened 2017-01-20 18:08 UTC
hi, tnx for reading carefully.
i use api like this:

```
require_once "Facebook/autoload.php";
        $fb = new Facebook\Facebook([
            'app_id' => 'xxxxxxx',
            'app_secret' => 'xxxxxxxxx',
            'default_graph_version' => 'v2.2'
        ]);
$pageAccessToken = 'xxxxxxxxxxxxxxxxxxxxx';

        $linkData = [
            'link' => $link,
            'message' => $message,
            'picture' => $pic
        ];

        try {
            $response = $fb->post('/me/feed', $linkData, $pageAccessToken);
        } catch (Facebook\Exceptions\FacebookResponseException $e) {
            echo 'Graph returned an error: ' . $e->getMessage();
        } catch (Facebook\Exceptions\FacebookSDKException $e) {
            echo 'Facebook SDK returned an error: ' . $e->getMessage();
        }
        $graphNode = $response->getGraphNode();
```

my problem is that, this code work sometimes, not all time. and in sometime i see these errors:

```
Severity: Notice
Message: Undefined offset: 1
Filename: Http/GraphRawResponse.php
Line Number: 108
```
and

```
Severity: 4096
Message: Argument 4 passed to Facebook\FacebookResponse::__construct() must be of the type array, null given, called in /home/deponews/public_html/application/controllers/Facebook/FacebookClient.php on line 225 and defined
Filename: Facebook/FacebookResponse.php
Line Number: 75
```
i go to api explorer , and select my page from drop down and at the bottom drop down , select access page token , then select my page name again. and copy generation token into my page access token.

i don't know why sometimes this code work well , and sometimes its not.

any idea ?

**Comment by yguedidi** [comment] 2017-06-24 16:46
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.

**Closed by yguedidi** 2017-06-24 16:46 UTC

**Comment by yourchoice** [comment] 2018-12-04 12:30
I have same Notice:

Undefined offset: 1 in ..../vendor/facebook/graph-sdk/src/Facebook/Http/GraphRawResponse.php on line 108

**Comment by lxgiang90** [comment] 2018-12-07 09:43
Please help me. 

> I have same Notice:
> 
> Undefined offset: 1 in ..../vendor/facebook/graph-sdk/src/Facebook/Http/GraphRawResponse.php on line 108

**Comment by andreiciceu** [comment] 2018-12-10 11:30
This is a problem in 5.5 branch of php-graph-sdk.
Caused by incorrectly parsing the status when HTTP2 is used: `HTTP/2 200` is not recognised by the regex at `Facebook/Http/GraphRawResponse.php: 107`.
Meanwhile, to fix it, I'm currently using: `|HTTP/\d\.?\d?\s+(\d+)\s+.*|` instead of the standard reg-ex at the above line

@yguedidi  this should be re-opened and fixed.
@facebook-github-bot reopen
