### ISSUE TITLE
Email Permission is granted but email does not return

### ISSUE THREAD

**Issue by leoapsilva** [facebook/php-graph-sdk#932] opened 2018-02-07 14:27 UTC
The user granted the 'email' permission, but the email does not been returned.
I've check all declined permissions then I call `$helper->getReRequestUrl`.
So, all permissions I asked are granted or the user cannot login.

![image](https://user-images.githubusercontent.com/11687748/35918342-92c503f2-0bf8-11e8-9193-95e0eaebbf05.png)

I've noted for some those users these permissions are not returned, only firends can have information about the user, and the profile on facebook is displayed like that (Look the "_To see what he shares with friends, send him a friend request._"):
![image](https://user-images.githubusercontent.com/11687748/35920549-4dd3b43a-0bff-11e8-90f2-bd6d069cb8f1.png)
![image](https://user-images.githubusercontent.com/11687748/35918489-1e928ed6-0bf9-11e8-92c0-3298f78962f8.png)

It was plausible the profile omitted for non-friends could not return some info.
AFAIK, this behaviour is not documented...

Searching for more users with the same problem, I found two users which the Facebook profile is 'wide opened' (see next picture).
For these users, the permission 'friends' returned info.
**But email was not returned.**
![image](https://user-images.githubusercontent.com/11687748/35918929-969d9302-0bfa-11e8-9e31-0dc978eb7496.png)
![image](https://user-images.githubusercontent.com/11687748/35920255-8386f57a-0bfe-11e8-8c19-d1f937afa434.png)
It happens with 4 from 30 users in one day. 
It is very severe...
I found more users with the same problem on issues #922 and #882.
Maybe they could not explain exactly what was their issues and could be the same of mine.

**Comment by gmertk** [comment] 2018-02-08 13:56
Hi @leoapsilva, it looks like it is actually related to the platform itself rather than this SDK. If you still get the same response from Graph Explorer https://developers.facebook.com/tools/explorer/145634995501895/ then the issue isn't related to the SDK.

**Comment by leoapsilva** [comment] 2018-02-16 17:48
Hi @gmertk, thanks for your reply. But I did not understand what the context of 'the platform itself'.
Could you elaborate more?
If I had the all the users authenticating and granting email permission and facebook 'omitting ' the email I would think it was my code. 
But some of them populate the index 'email' of facebook's return array and some does not as I sad.
Do you have any other idea? 
Thanks in advance

**Comment by leoapsilva** [comment] 2018-02-16 18:06
Hi @gmertk, as you suggest, I found the token of some users the **email permission is granted** but the email does not return and put on Graph Explorer.
As I expected, the email of this user does not return as you can see below:

![image](https://user-images.githubusercontent.com/11687748/36321796-3733ab7e-1332-11e8-8ee0-b806dda83099.png)

![image](https://user-images.githubusercontent.com/11687748/36322051-1dcaba78-1333-11e8-8621-586a9984d1a9.png)

Maybe it is an issue on SDK...

**Comment by gmertk** [comment] 2018-02-16 21:14
Hi @leoapsilva if you click the "Show" button next to "3 Debug Messages", you can see the warning about missing email. As I mentioned, this isn't about the PHP SDK. Facebook Platform doesn't return the email by design when the email isn't reachable or when the user doesn't have a confirmed email.

**Comment by yguedidi** [comment] 2018-02-25 12:48
Thanks for the report! And special thanks to @gmertk for help solving this issue!

Here what the doc says:
![image](https://user-images.githubusercontent.com/1480128/36641585-21df15a4-1a32-11e8-83bc-e7a5862f8df9.png)

So I'm closing this as it looks like not and SDK issue, but a user who changes his/her email adress to an invalid one.

**Closed by yguedidi** 2018-02-25 12:48 UTC

**Comment by simeyla** [comment] 2018-12-03 23:03
I think this can most commonly occur when someone join using just a phone number too. That's probably more frequent than it used to be so your app needs to test for that scenario.
